#ifndef ECU_OD_CFG_H
#define ECU_OD_CFG_H

typedef enum{
	ECU_OD_INFO_ID_CNT=50,
	ECU_OD_INFO_ID_TMP=60,
	ECU_OD_INFO_ID_LIGHT=70
}ECU_OD_INFO_ID_t;
typedef enum{
	ECU_OD_MODE_INFO_ID=80,
	ECU_OD_MODE_INFO_CNT=90,
	ECU_OD_MODE_INFO_TMP=100,
	ECU_OD_MODE_INFO_LIGHT=110
}ECU_OD_MODE_t;
enum{
	ECU_OD_CNT_OFF=120,
	ECU_OD_CNT_ON=130,
	ECU_OD_LIGHT_MORNING=140,
	ECU_OD_LIGHT_NIGHT=150
};
typedef struct{
	UINT8_t Temp,Light,State;
}ECU_OD_DATA_t;
extern ECU_OD_DATA_t ECU_OD_Data;
#endif
